# Generated by Django 5.0.1 on 2025-12-06 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_add_pending_outgoing_message'),
        ('messaging', '0001_initial'),
        ('oauth', '0002_add_pending_outgoing_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOutgoingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=36)),
                ('platform', models.CharField(max_length=50)),
                ('platform_conversation_id', models.CharField(max_length=255)),
                ('recipient_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pending_outgoing_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='idx_messages_unread',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_convers_8904b4_idx',
            old_name='messages_convers_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_sent_at_cea072_idx',
            old_name='messages_sent_at_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='media_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='idx_messages_is_read'),
        ),
        migrations.AddField(
            model_name='pendingoutgoingmessage',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_messages', to='oauth.connectedaccount'),
        ),
        migrations.AddField(
            model_name='pendingoutgoingmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_messages', to='conversations.conversation'),
        ),
        migrations.AddIndex(
            model_name='pendingoutgoingmessage',
            index=models.Index(fields=['user_id', 'platform', 'status'], name='pending_out_user_id_943060_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingoutgoingmessage',
            index=models.Index(fields=['created_at'], name='pending_out_created_94bfde_idx'),
        ),
    ]
