# Generated by Django 5.0.1 on 2025-12-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_account_433548_idx',
            old_name='conversati_account_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_last_me_99c95c_idx',
            old_name='conversati_last_me_idx',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participant_avatar_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
