# Generated by Django 5.0.1 on 2025-12-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='connectedaccount',
            new_name='connected_a_user_id_a60e05_idx',
            old_name='connected_a_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='connectedaccount',
            new_name='connected_a_platfor_ff48b7_idx',
            old_name='connected_a_platfor_idx',
        ),
        migrations.AlterField(
            model_name='connectedaccount',
            name='access_token',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='connectedaccount',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('gmail', 'Gmail')], max_length=50),
        ),
        migrations.AlterField(
            model_name='connectedaccount',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
